#pragma once

#define APP_TITLE "ESP32CAM-RTSP-ONVIF"
#define APP_VERSION "2.0"

#define WIFI_SSID "ESP32CAM-RTSP-ONVIF"
#define WIFI_PASSWORD nullptr
#define CONFIG_VERSION "2.0"

#define OTA_PASSWORD "ESP32CAM-RTSP-ONVIF"

#define RTSP_PORT 554
#define ONVIF_PORT 8080

// ONVIF Device Information
#define ONVIF_MANUFACTURER "ESP32-CAM"
#define ONVIF_MODEL "ESP32-CAM-RTSP-ONVIF"
#define ONVIF_FIRMWARE_VERSION "2.0"
#define ONVIF_SERIAL_NUMBER "ESP32CAM"
#define ONVIF_HARDWARE_ID "ESP32-CAM"

#define DEFAULT_FRAME_DURATION 200
#define DEFAULT_FRAME_SIZE "VGA (640x480)"
#define DEFAULT_JPEG_QUALITY (psramFound() ? 12 : 14)

#define DEFAULT_BRIGHTNESS 0
#define DEFAULT_CONTRAST 0
#define DEFAULT_SATURATION 0
#define DEFAULT_EFFECT "Normal"
#define DEFAULT_WHITE_BALANCE true
#define DEFAULT_WHITE_BALANCE_GAIN true
#define DEFAULT_WHITE_BALANCE_MODE "Auto"
#define DEFAULT_EXPOSURE_CONTROL true
#define DEFAULT_AEC2 true
#define DEFAULT_AE_LEVEL 0
#define DEFAULT_AEC_VALUE 300
#define DEFAULT_GAIN_CONTROL true
#define DEFAULT_AGC_GAIN 0
#define DEFAULT_GAIN_CEILING "2X"
#define DEFAULT_BPC false
#define DEFAULT_WPC true
#define DEFAULT_RAW_GAMMA true
#define DEFAULT_LENC true
#define DEFAULT_HORIZONTAL_MIRROR false
#define DEFAULT_VERTICAL_MIRROR false
#define DEFAULT_DCW true
#define DEFAULT_COLORBAR false

#define DEFAULT_LED_INTENSITY 0